services:
  test-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - opentable-db:/var/lib/postgresql/data
    restart: on-failure
volumes:
  opentable-db: